url: https://github.com/piraeusdatastore/helm-charts.git
subdirectory: charts/snapshot-controller
commit: 380a339ed3b9108e26eb03805c91525ed016e21e
packageVersion: 1
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
